name = "ikk"
license = "MIT"
licenselink = "https://github.com/jingziming/hugo-theme-ikk/blob/master/LICENSE.md"
description = ""
homepage = "http://jingziming.com/"
tags = []
features = []
min_version = "0.22.1"

[author]
  name = "jingziming"
  homepage = "http://jingziming.com/"